#!/bin/csh
#==================================================================
#SBATCH -J fv32wrf
#SBATCH -o log.out.fv32wrf2019_%j
#SBATCH -e log.err.fv32wrf2019_%j
#SBATCH -A smallqueue
#SBATCH -p workq
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=24
#SBATCH -t 02:00:00

#set echo

set base_dir = /oldscratch/ywang/EPIC/Program/WoFS_post

# cd to directory where job was submitted from
cd ${base_dir}

# User defined variables:
if ($#argv < 1) then
  echo "usage $0 YYYYMMDDHH"
  exit
endif

set datestr = $1
set fcstdate = `echo $datestr | awk '{print substr($0,1,8)}'`
set fcsthour = `echo $datestr | awk '{print substr($0,9,2)}'`

#set date = 20190520
set fcst_base = /scratch/ywang/EPIC/test_runs

set times = ($fcsthour)
set nt = (37)

# Run wrapper script for forecast:

setenv MALLOC_MMAP_MAX 0
setenv MALLOC_TRIM_THRESHOLD 536870912
#set PYTHON = /scratch/software/Odin/python/anaconda2/bin/python
#setenv PATH /scratch/software/Odin/python/anaconda2/bin:$PATH
set PYTHON = /home/louis.wicker/anaconda2/envs/wof/bin/python
setenv PATH /home/louis.wicker/anaconda2/envs/wof/bin:$PATH

sleep 1

set i = 1
foreach dir ($times)

   set fcstdir = "${fcst_base}/$fcstdate$dir"
   set summarydir = "${fcst_base}/$fcstdate$dir"

   #
   # Build directories needed:
   #
   if ( ! -d $summarydir) then
     mkdir -p $summarydir
   endif
   #set flagdir = "${fcst_base}/$date$dir/flags/"
   #if ( ! -d $flagdir) then
   #  mkdir -p $flagdir
   #endif
   #
   #set flagfile = "$flagdir/done.fv32wrf"

   echo "fcstdir = $fcstdir"
   #echo $flagfile
   echo "summarydir = $summarydir"

   set tempnt = $nt[$i]
   echo $tempnt

   if ( -d $fcstdir ) then
      #if ( ! -e $flagfile ) then
         $PYTHON wrapper_post_fv32wrf.py -d $fcstdir -o $summarydir -e $tempnt
         #touch $flagfile
      #endif
   endif
   @ i++
end

sleep 10

