#!/bin/csh
#==================================================================
#SBATCH -J post_ens
#SBATCH -o /oldscratch/larissa.reames/fv3sar_post/logs/post_ens.out
#SBATCH -e /oldscratch/larissa.reames/fv3sar_post/logs/post_ens.err
#SBATCH -A smallqueue
#SBATCH -p workq
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=24
#SBATCH -t 01:00:00

set echo

set base_dir = /oldscratch/ywang/EPIC/Program/WoFS_post

# cd to directory where job was submitted from
cd ${base_dir}

#$SLURM_SUBMIT_DIR

setenv MALLOC_MMAP_MAX 0
setenv MALLOC_TRIM_THRESHOLD 536870912
set PYTHON = /scratch/software/Odin/python/anaconda2/bin/python
setenv PATH /scratch/software/Odin/python/anaconda2/bin:$PATH

# User defined variables:

set date = 20190520
set fcst_base = /scratch/ywang/EPIC/test_runs
#set fcst_base = /scratch/jtti/realtime/FCST/

#set times = (1900 1930 2000 2030 2100 2130 2200 2230 2300 2330 0000 0030 0100 0130 0200 0230 0300)
#set nt = (72 36 72 36 72 36 72 36 72 36 72 36 72 36 72 36 72)

#set times = (1900 2000 2100 2200 2300 0000)
#set nt = (72 60 48 36 24 12)

set times = (18)
set nt = (37)

# Run wrapper script for forecast:

sleep 1

set i = 1

foreach dir ($times)
   set fcstdir = "${fcst_base}/$date$dir"
   #set flagfile = $flagdir"/"$dir"_ens.txt"
   set tempsumdir = "${fcst_base}/$date$dir"


   echo $fcstdir
   echo $tempsumdir

   set tempnt = $nt[$i]
   echo $tempnt

   if ( -d $fcstdir ) then
      #if ( ! -e $flagfile ) then
         $PYTHON wrapper_post_ens.py -d $fcstdir -o $tempsumdir -e $tempnt
         #touch $flagfile
         #exit(0)
      #endif
   endif
   @ i++
end

sleep 10

